# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 70e9045d09bca6f9d30ac9f1aa32f3e0cbec2c4f

{
  "title": "Нечто7",
  "description": "Неведомое7"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/15/
Content-Type: application/json
Authorization: Token 70e9045d09bca6f9d30ac9f1aa32f3e0cbec2c4f

{
  "status": "CLOSED"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/2/
Content-Type: application/json
Authorization: Token 0ca7678daa582469157ca8a4a504418e98c2e39c

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_after=2020-10-01
Content-Type: application/json

###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=CLOSED
Content-Type: application/json

###

# попытка удалить
DELETE {{baseUrl}}/advertisements/20/
Content-Type: application/json
Authorization: Token 70e9045d09bca6f9d30ac9f1aa32f3e0cbec2c4f

###